### ISSUE TITLE
[Crash]: LongSwords (any type) crash the game when held

### ISSUE THREAD

**Issue by FuryJack07** [Yesssssman/epicfightmod#1688] opened 2024-07-03 20:51 UTC
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [x] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

whenever you grab any longsword in your main hand, the game crashes

Crash report:
https://pastebin.com/Rri2ScqS

Mod list:
https://pastebin.com/tLE5GUd7

How to reproduce:
get in any world, survival, creative, doesn't matter, grab a longsword, and the moment it enters your main hand the game crashes.

(note, it's not the weapon class, as grabbing a modded weapon that got classified as a longsword, like for example the heartseeker in the modpack i'm using, doesn't crash the game)

**Comment by qVoidreaver** [comment] 2024-07-05 07:35
I had the same problem, and when I removed the Epic Fight Battle Styles mod this problem was solved

**Comment by Yesssssman** [comment] 2024-07-05 10:13
> I had the same problem, and when I removed the Epic Fight Battle Styles mod this problem was solved

Thank you so much I have struggled to find the cause since yesterday. I'll check what exactly caused this crash

**Comment by Forixaim** [comment] 2024-07-05 18:33
Hey everyone,

I'll be on my way to reproduce the crash and try to fix it. It may be caused by a null predicator registry of the longsword I overrode. 

Cheers
    Forixaim (EF - BS)

**Comment by Yesssssman** [comment] 2024-07-06 04:04
This issue will be fixed in the next release of Epic Fight Battle System (Maybe 1.2.4)

**Comment by Yesssssman** [comment] 2024-08-05 13:50
I checked this issue no longer occurs in the latest epic fight battle styles.

**Closed as completed by Yesssssman** 2024-08-05 13:50 UTC
Labels: external issue, crash, solved
