### ISSUE TITLE
Ender Dragon can't deal damage nor stun. [1.18.2, Forge 40.1.54]

### ISSUE THREAD

**Issue by Sazuzaki** [Yesssssman/epicfightmod#1094] opened 2022-07-23 23:51 UTC
Heyo, the Ender Dragon cannot hit the player in later forge versions. In this instance, 40.1.54. 

https://youtu.be/oLKVamwWG-o

Epic Fight is the only mod installed, and I entered The End in survival.

**Comment by Yesssssman** [comment] 2022-07-23 23:53
Try downgrading the forge version to 40.1.0.

**Comment by Sazuzaki** [comment] 2022-07-23 23:56
> Try downgrading the forge version to 40.1.0.

Sure thing, just thought I'd bring it up since mods like Patchouli or Neat need forge 40.1.51 or higher. Thanks for the super quick reply though!

**Comment by Yesssssman** [comment] 2022-07-25 11:35
Could you tell me if it's solved?

**Comment by lucafer1** [comment] 2022-07-26 13:28
x2
In my case I have tried to use version 40.1.0. And the problem is solved i see.
The point is that it only works there it seem. I tried 4.1.25 and the problem exist too.
I tried that version because in my modpack I have "beyond earth mod" and it is the compatible version.

**Comment by MetalKnight56** [comment] 2022-07-29 04:53
> x2 In my case I have tried to use version 40.1.0. And the problem is solved i see. The point is that it only works there it seem. I tried 4.1.25 and the problem exist too. I tried that version because in my modpack I have "beyond earth mod" and it is the compatible version.

As of now, forge is being quite inconsistent with its updates, often breaking mods and such, once forge has a new stable version epic fight will updte to newer versions aswell, as mentioned by Yesman, the lead developer of the project.

**Comment by ShadeKage** [comment] 2022-07-29 06:01
I havent even tried the end yet and im on forge 40.1.55, and some other mods i got need that version.. miiight be best to try and fix the incompatibility so not EVERYONE has to downgrade

**Comment by Yesssssman** [comment] 2022-08-13 11:13
Fixed in 18.3.0

**Closed by Yesssssman** 2022-08-13 11:13 UTC
Labels: working
