### ISSUE TITLE
Mob is throwing a null pointer and has corrupted a world

### ISSUE THREAD

**Issue by Icebelly** [Yesssssman/epicfightmod#929] opened 2022-04-11 07:04 UTC
Might be good to have a report format, not sure what all I should fill out here but my world has seemingly been corrupted possibly due to something with the ChasingGoal? I'm not versed in java or code but it's just my best guess from reading the crash log.
[latest.log](https://github.com/Yesssssman/epicfightmod/files/8461715/latest.log)

**Comment by Yesssssman** [comment] 2022-04-11 17:34
Are there any other mods regarding the AI?

**Comment by Icebelly** [comment] 2022-04-12 00:13
Not entirely sure if any of these really affect the AI but notable I'm running Project MMO, Champions and Brutal Bosses, though there weren't any bosses in range of me where I've been stuck crashing as they only spawn on world gen and I only started crashing after respawning at my home.

**Comment by Yesssssman** [comment] 2022-04-12 05:07
The cause of your crash is a zombie. Have you installed any mod that affects the zombie's AI?

**Comment by Icebelly** [comment] 2022-04-12 07:22
Figured it out, it's some issue with [Champions ](https://www.curseforge.com/minecraft/mc-mods/champions) specifically the artic or enkindling modifiers on zombies as it causes them to shoot off homing projectiles similar to shulkers. It only crashes once the zombie with this modifier gets within follow range. So this might be more of a champions issue than an epic fight issue.

**Comment by Yesssssman** [comment] 2022-04-25 23:59
So.. as I said in #959, it's not a mod incompatibility issue. But what you said in the last is not a same kind of crash I guess

**Comment by Yesssssman** [comment] 2022-05-02 11:05
So the first crash was fixed in 18.1.5. If you have another problem, please open a new issue tab

**Closed by Yesssssman** 2022-05-02 11:05 UTC
Labels: crash, working
