### ISSUE TITLE
[Bug]: Elytra glitch

### ISSUE THREAD

**Issue by DragonAstemirN** [Yesssssman/epicfightmod#1185] opened 2022-09-15 16:39 UTC
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5/1.18.2

### What happened?

The game crashes when attacking any entity. when a blow is given it blocks.

error with elytra remains, broken column animation when using rockets

https://user-images.githubusercontent.com/94336869/190459403-b5d04727-a3a8-47a9-937e-f274433de931.mp4

**Comment by Yesssssman** [comment] 2022-09-15 22:56
Crash repo?

**Comment by MetalKnight56** [comment] 2022-10-09 21:50
Try using the latest forge version

**Comment by DragonAstemirN** [comment] 2022-10-12 18:42
test without any other mod the error continues only with epic-fight mod broken column when using rockets

forge version 36.2.39
epic-fight version:16.6.3.

**Comment by MetalKnight56** [comment] 2022-10-12 18:50
> Author

Yeah just confirmed that the issue is indeed on our end, thanks

**Comment by MetalKnight56** [comment] 2022-11-14 20:42
@Yesssssman Yeah while editting animations just checked that this is persistant in all version, both on 1.16.5 and 1.18.2

**Comment by MetalKnight56** [comment] 2023-07-09 02:50
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users

**Closed by MetalKnight56** 2023-07-09 02:50 UTC
Labels: bug, enhancement
