### ISSUE TITLE
[Bug|Crash]:  Crashes when entering combat mode with Vampirism in 1.20.1

### ISSUE THREAD

**Issue by Snowiro** [Yesssssman/epicfightmod#1801] opened 2024-09-06 05:36 UTC
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Vampirism version 1.10.9

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Playing in 1.20.1 multiplayer lan after my friend became a vampire when they enter combat mode my client crashes and whenever they join my world my game crashes again, I'm assuming its because they crashed and got stuck in combat mode while being a vampire my other friends can still join and enter combat mode.

I tried becoming a vampire while not hosting but it does not crash my game when in combat mode.

Crash report and mod list https://pastebin.com/ZeVYbnEK

### Steps to Reproduce

Have Epic fight and Vampirism installed
Host lan server
Have someone be a vampire
Let them enter combat mode

**Comment by guivnf** [comment] 2024-09-06 13:27
Closing issue as user did not narrow down the issue. Crash is not caused by vampirism.

**Closed as not planned** 2024-09-06 13:27 UTC
Labels: policy violation

**Comment by Snowiro** [comment] 2024-09-06 15:02
Sorry about that after a few more digging its Yes steve model alongside with timeclock mod
