### ISSUE TITLE
[Bug|Crash]: Battle mode doesn't allow me to attack

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1401] opened 2023-10-16 14:14 UTC
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

This is a very specific bug that is also very difficult to trigger or sometimes comes up and sometimes goes awayLuckily I found a way to trigger it.

https://github.com/Yesssssman/epicfightmod/assets/130232431/32972bd8-30a5-49a8-928f-1fd1454605f1

Luckily, I found a trigger.

First you need to install a new Minecraft, download Epic Fight, then start the game, load it once, then quit, and then download other mods to load it because this bug will only trigger once, some mods installed and then start the game, this problem will occur, However, they are fully compatible with Epic Fight, and when this bug appears, it will only disappear by restarting the game a few times, basically every time a new mod is installed to load.

This bug occurs whenever a new mod installation is loaded for the first time.

Currently locked to several mods "bad_npcs", "geckolib", including "Weapons Of Miracles"

https://github.com/Yesssssman/epicfightmod/assets/130232431/87aa38b6-8559-427e-bbba-b5e0af7203cf

The keys are all default.

The versions I tested are 1.18.2 and 1.20.1 which are both using the latest Forge and Epic fight up to now.
Minecraft 1.18.2
Forge 40.2.10
Epic Fight 18.5.13 or Epic Fight 18.5.14 because 1.18.2 was tested earlier so I don't really remember but those are the two versions tested.

Minecraft 1.20.1
Forge 47.2.1
Epic Fight 20.5.15

1.19.2 should also have this problem because I did not test 1.19.2, so I do not know that this is a serious bug. This bug breaks some mod compatibility. As long as you load a new mod, you will have the probability to trigger the mod Restart the game with a new mod after this happens and the bug will disappear, but if a new mod is loaded then the problem will reappear as described above and so on.

Although I know there are similar issues but they do not tell you the cause of the problem in detail the current 1.20.1 version of the "bad_npcs" mod the first new load will occur 100% of the problem including some other mods and even Epic Fight sometimes has this problem on its own including "Weapons Of Miracles".

1.18.2 is similar to 1.20.1 above.

**Comment by fzrdwa123456** [comment] 2023-10-16 14:16
Because I'm using a translator there's a bit of a problem with the description.

**Comment by fzrdwa123456** [comment] 2023-10-16 14:17
This bug must rely on other mods to trigger the first new load but it seems Epic Fight itself will also trigger.

**Comment by fzrdwa123456** [comment] 2023-10-16 14:35
I just tested Epic Fight 18.5.15, maybe because you added a new button change so the bug seems to trigger without a problem, but the new version of your default button conflict.

**Comment by Vlr0** [comment] 2024-01-23 18:51
The same issue has happened with my little brother, we are both on the same server but it seems that battle mode doesn't detect that he is attacking, he can also mine while in battle mode even tho we have mining disabled, and I cannot see him attacking in battle mode nor can he but we can both see me attacking we also have the W.O.M mod installed to see if that would fix the problem but no, there are no animations what so ever when he is attacking, he cannot use duel wield nor multi-attack.

**Comment by Yesssssman** [comment] 2024-08-23 07:45
The cause of this bug is known as when you respawn after your model completely disappears and turns into smoke (The smoke particles when entities die).

It has only been fixed in 1.20.1 since we only support that version now.

**Closed by Yesssssman** 2024-08-23 07:45 UTC
Labels: solved
