### ISSUE TITLE
[Bug|Crash]: Jet and Elia's armor resource resolution or something

### ISSUE THREAD

**Issue by MistaCursed** [Yesssssman/epicfightmod#1502] opened 2024-01-14 23:26 UTC
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Jet and Elia's Armors

### Minecraft Version

1.18.2

### What happened?

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-01-15 01:12
Description: Stitching

net.minecraft.client.renderer.texture.StitcherException: Unable to fit: jet_and_elias_armors:items/takemarubootsitem, size: 544x371, atlas: 8160x8176, atlasMax: 8192x8192 - Maybe try a lower resolution resourcepack?
	at net.minecraft.client.renderer.texture.Stitcher.m_118193_(Stitcher.java:71) ~[client-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.texture.TextureAtlas.m_118307_(TextureAtlas.java:383) ~[client-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,xf:OptiFine:default,re:classloading,pl:rei_plugin_compatibilities:B,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:atlas.AtlasDataMixin,pl:mixin:A}
	at net.minecraft.client.resources.model.ModelBakery.processLoading(ModelBakery.java:266) ~[client-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraftforge.client.model.ForgeModelBakery.<init>(ForgeModelBakery.java:61) ~[forge-1.18.2-40.2.17-universal.jar%23300!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:quark.mixins.json:client.accessor.AccessorModelManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:quark.mixins.json:client.accessor.AccessorModelManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.18.2-20220404.173914-srg.jar%23295!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames,pl:rei_plugin_compatibilities:B,re:mixin}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames,pl:rei_plugin_compatibilities:B,re:mixin}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

**Comment by MetalKnight56** [comment] 2024-01-15 04:04
Denied as user has Optifine & duplicate of #1404

**Closed by MetalKnight56** 2024-01-15 04:04 UTC
Labels: denied
