### ISSUE TITLE
[Bug|Crash]: random crash on dedicated server

### ISSUE THREAD

**Issue by Aabaddon** [Yesssssman/epicfightmod#1624] opened 2024-04-29 23:29 UTC
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

It crashes when trying to connect to my dedicated server, if it doesnt crash and i access the server the next time i try to connect it gives a "netty io" error

Thread: Render thread
Suspected Mod: 
	Epic Fight (epicfight), Version: 20.7.4
		at TRANSFORMER/epicfight@20.7.4/yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.getStamina(PlayerPatch.java:343)
Stacktrace:
	at net.minecraft.network.syncher.SynchedEntityData.m_135370_(SynchedEntityData.java:120) ~[client-1.20.1-20230612.114412-srg.jar%23572!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.SynchedEntityDataMixin,pl:mixin:APP:lithium.mixins.json:entity.data_tracker.use_arrays.DataTrackerMixin,pl:mixin:APP:lithium.mixins.json:entity.data_tracker.no_locks.DataTrackerMixin,pl:mixin:A}

**Comment by longsosos** [comment] 2024-05-08 16:15
I have the same problem with you. Epic Fight Mod work normally in single-player but in multi-player it also relates to a NullPointerException within the SynchedEntityData class, specifically when trying to invoke a method on a null object returned by a call within the Minecraft code. This problem is occurring in the context of the Epic Fight mod, as indicated by the stack trace referencing EpicFight classes like PlayerPatch and LocalPlayerPatch.
Have you find any solution to this ?

**Comment by DeshiDesu** [comment] 2024-05-12 14:39
Having the same issue and I narrowed it down to being caused by origins mod by having not rendering the player BEFORE the choosing origins process. This wont be a problem in singleplayer but on some occasions the server asks for player data from the client between this process.

**Comment by Yesssssman** [comment] 2024-06-23 08:18
Please upload a full log.

**Comment by DeshiDesu** [comment] 2024-06-23 08:40
> Having the same issue and I narrowed it down to being caused by origins mod by having not rendering the player BEFORE the choosing origins process. This wont be a problem in singleplayer but on some occasions the server asks for player data from the client between this process.

For the record, what I said was a complete hypothesis and should not at all be taken at face value. I haven't been able to deduce why it was causing the problem but I have already moved on by removing said problem which in my case was the Origins mod. Good luck to all having this issue.

**Comment by MWArctic** [comment] 2024-06-23 10:36
Coming over from: #1671 

Here is my current full log for the same/similar crash: 
[latest (1).log](https://github.com/user-attachments/files/15944183/latest.1.log)

I personally have a long list of mods, so in a couple hours I will see if I can find any particular mod causing this issue.

**Comment by Yesssssman** [comment] 2024-06-23 11:58
When I tested only Epic Fight and Origins installed, I got no crash in the dedicated server. Please specify the exact causion for this issue. It will be really appreciated.

**Comment by DeshiDesu** [comment] 2024-06-23 18:21
> When I tested only Epic Fight and Origins installed, I got no crash in the dedicated server. Please specify the exact causion for this issue. It will be really appreciated.

Sorry for being unclear. I meant to say it a set of mods that caused it, however I never really got to the bottom of it since the crash happened by pure chance with no clear indicator from the logs. Removing Origins was the only solution I've found and I never had this issue again after that. This problem arose for me a long time ago, I don't exactly remember which set of mods that caused it but I do know that it was a headache to debug it.

**Comment by MWArctic** [comment] 2024-06-24 03:18
On my end, it's been narrowed down to an incompatibility with Ars Nouveau causing my crash, sucks that it happens to be two of the main mods I want to use conflicting.

**Comment by Yesssssman** [comment] 2024-06-24 05:34
I can't reproduce the crash. Can you tell me how I can get it?

![image](https://github.com/Yesssssman/epicfightmod/assets/79469058/05caf559-12f8-41fa-a1ed-b4ecb91eb57b)

**Comment by HypnoticChris** [comment] 2024-07-11 05:04
I also have this exact same crash currently, and as op said, only having the issue when connecting to a server. Singleplayer works perfectly fine. Unlike the op, I do not have Origins, but I do have Ars Nouveau (not to say either of those are direct issues). The server in which I am trying to connect to boots perfectly fine, however the client cannot connect and gets a crash. The crash log links ModernFix and Oculus along with Epic Fight for suspected mods.
-- Head --
Thread: Render thread
Suspected Mods: 
	Epic Fight (epicfight), Version: 20.7.4
		at TRANSFORMER/epicfight@20.7.4/yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.getMaxStunShield(LivingEntityPatch.java:318)

	ModernFix (modernfix), Version: 5.18.6+mc1.20.1
		Issue tracker URL: https://github.com/embeddedt/ModernFix/issues
		Mixin class: org.embeddedt.modernfix.forge.mixin.bugfix.entity_pose_stack.LivingEntityRendererMixin
		Target: net.minecraft.client.renderer.entity.LivingEntityRenderer
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.LivingEntityRenderer.redirect$zhe001$fireCheckingPoseStack(LivingEntityRenderer.java:1020)

	Oculus (oculus), Version: 1.7.0
		Issue tracker URL: https://github.com/Asek3/Oculus/issues
		Mixin class: net.irisshaders.iris.mixin.LevelRendererAccessor
		Target: net.minecraft.client.renderer.LevelRenderer
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.invokeRenderEntity(LevelRenderer.java)

**Comment by HypnoticChris** [comment] 2024-07-11 05:09
Issue solved by removing ModernFix on client, not sure if it will fix the issue for the above comments.

**Comment by Yesssssman** [comment] 2024-08-10 03:42
Fixed in 20.8.7

**Closed by Yesssssman** 2024-08-10 03:42 UTC
Labels: low information, mod incompatibility, crash, solved
